- menu_name: "Services"

- name: "Contact"   #TODO
  url: "/contact/"
  title: "Contact"

- name: "Newsletter"    #TODO
  url: "/feed.xml"
  title: "Subscribe to the newsletter"

- name: "Privacy"   #TODO
  url: "/atom.xml"
  title: "Privacy"

- name: "Cookies"
  url: "/atom.xml"  #TODO
  title: "Cookies"


- name: "sitemap.xml"   # TODO
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
